[package]
name = "rterm"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
clap = { version = "4.5.6", features = ["derive"] }
ctrlc = "3.4.4"
device_query = "2.1.0"
serialport = "4.3.0"
termios = "0.3.3"
